routes/web.php
<?php


// Auth::loginUsingId(1);

// Auth::routes();
    
Route::group(array('domain' => Config("subdom.second_dom")), function () {
    
    Route::get('/590d38f0603ef5a8a7be6c452438d609/{id}', 'Customer\CustomerHelper@verificationuser')->name('verificationuser');
    Route::get('/donate', function(){
            return \view('donateview');
    })->name('donateview');

    // Password Reset Routes...
    // Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    // Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    // Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::get('user/change-password/{token}', 'MailService\MailServiceController@forgotpasswordform')->name('changepassword');
    Route::post('user/change-password', 'MailService\MailServiceController@forgotpasswordpost')->name('changepasswordpost');
    Route::post('user/reset-password', 'MailService\MailServiceController@forgotpassword');

});

    Route::get('testt', function(){
        $user = \App\Models\User::find(239);
        return \App\Http\Controllers\MailService\MailServiceController::KonfirmasiPendaftaran($user);
    });
Route::group(array('domain' => Config("subdom.first_dom")), function () {



    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    // Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('/admin/logout','HomeController@logout')->name('logout');
    // Registration Routes...
    // Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    // Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');


    Route::get('/','HomeController@index')->name('index');
    Route::group(['prefix' => 'admin', 'middleware' => 'superadmin'], function() {
                
        Route::get('/home', 'HomeController@dashboard')->name('dashboard');
            
            // USERS //

            Route::group(['namespace' => 'Users', 'as' => 'users.'], function () {
                Route::get('users-list', 'UsersController@index')->name('list');
                Route::get('users-add', 'UsersController@UsersAdd')->name('store');
                Route::post('users-add', 'UsersController@UsersPost')->name('add');
                Route::get('users/detail/{id}', 'UsersController@show')->name('detail');
                Route::get('users/edit/{id}', 'UsersController@Usersedit')->name('edit');
                Route::get('users/delete/{id}', 'UsersController@Usersdestroy')->name('delete');
                Route::post('users/{id}', 'UsersController@update')->name('update');
                Route::get('users-ajax-getdata', 'UsersController@getData')->name('ajax.getdata');
                Route::get('users/detail/ajax{id}', 'UsersController@getDataDetail')->name('ajax.getdata.detail');
                Route::get('users/detail/delete/{id}', 'UsersController@detailDelete')->name('detail.delete');

            });    

             // OUR PARTNER //

                Route::group(['namespace' => 'OurPartner', 'as' => 'partner.'], function () {
                    Route::get('partner-list', 'OurPartnerController@index')->name('list');
                    Route::get('partner-add', 'OurPartnerController@PartnerAdd')->name('store');
                    Route::post('partner-add', 'OurPartnerController@PartnerPost')->name('add');

                    Route::get('partner/edit/{id}', 'OurPartnerController@Partneredit')->name('edit');
                    Route::get('partner/delete/{id}', 'OurPartnerController@Partnerdestroy')->name('delete');
                    Route::post('partner/{id}', 'OurPartnerController@update')->name('update');
                    Route::get('partner-ajax-getdata', 'OurPartnerController@getData')->name('ajax.getdata');
                    Route::get('partner/detail/ajax{id}', 'OurPartnerController@getDataDetail')->name('ajax.getdata.detail');
                    Route::get('partner/detail/delete/{id}', 'OurPartnerController@detailDelete')->name('detail.delete');

                });    
        
           // NEWSLETTER //

                Route::group(['namespace' => 'NewsLetter', 'as' => 'newsletter.'], function () {
                    Route::get('newsletter-list', 'NewsLetterController@index')->name('list');
                    Route::get('newsletter-add', 'NewsLetterController@NewsLetterAdd')->name('store');
                    Route::post('newsletter-add', 'NewsLetterController@NewsLetterPost')->name('add');
                    Route::get('newsletter/edit/{id}', 'NewsLetterController@NewsLetteredit')->name('edit');
                    Route::get('newsletter/delete/{id}', 'NewsLetterController@NewsLetterdestroy')->name('delete');
                    Route::post('newsletter/{id}', 'NewsLetterController@update')->name('update');
                });    

            // ABOUT //

            Route::group(['namespace' => 'About', 'as' => 'about.'], function () {
                Route::get('about-list', 'AboutController@index')->name('show');
                Route::post('about-update', 'AboutController@update')->name('update');

            });   

            // ACL //

            Route::group(['namespace' => 'Acl'], function () {

                Route::get('/users-group', 'controller\AclGroupController@index')->name('users-group');
                Route::get('/users-group/create', 'controller\AclGroupController@create')->name('users-group.create');
                Route::post('/users-group', 'controller\AclGroupController@store')->name('users-group.store');
                Route::get('/users-group/{id}', 'controller\AclGroupController@show')->name('users-group.show');
                Route::put('/users-group/{id}', 'controller\AclGroupController@update')->name('users-group.update');
                Route::get('/users-group/delete/{id}', 'controller\AclGroupController@delete')->name('users-group.delete');
            });   


            //SCAVENGER


            Route::group(['namespace' => 'Scavenger', 'as' => 'scavenger.'], function () {

                Route::get('scavenger-list', 'ScavengerController@index')->name('list');
                Route::get('scavenger-add', 'ScavengerController@ScavengerAdd')->name('store');
                Route::post('scavenger-add', 'ScavengerController@ScavengerPost')->name('add');
                Route::get('scavenger/detail/{id}', 'ScavengerController@show')->name('detail');
                Route::get('scavenger/edit/{id}', 'ScavengerController@Scavengersedit')->name('edit');
                Route::post('scavenger/{id}', 'ScavengerController@ScavengerUpdate')->name('update');
                Route::get('scavenger/delete/{id}', 'ScavengerController@Scavengerdestroy')->name('delete');
                Route::post('scavenger/{id}', 'ScavengerController@update')->name('update');
                Route::get('scavenger-ajax-getdata', 'ScavengerController@getData')->name('ajax.getdata');
                Route::get('scavenger/detail/ajax{id}', 'ScavengerController@getDataDetail')->name('ajax.getdata.detail');
                Route::get('scavenger/detail/delete/{id}', 'ScavengerController@detailDelete')->name('detail.delete');
            });

            //DOCUMENT
            Route::group(['namespace' => 'Document', 'as' => 'document.'], function () {
                Route::get('document/detail/{id}', 'DocumentController@documentShow')->name('detail');
                Route::post('document/{id}', 'DocumentController@documentUpdate')->name('update');
                Route::get('document/delete/{id}', 'DocumentController@documentDestroy')->name('delete');
                Route::get('document-ajax-getdata', 'DocumentController@getData')->name('ajax.getdata');
                Route::get('document-ajax-getmodal/{id}', 'DocumentController@getModal')->name('ajax.getmodal');
            });

            //DONATION
            Route::group(['namespace' => 'Donation', 'as' => 'donation.'], function () {
                Route::get('donation-list', 'DonationController@index')->name('list');
                Route::get('donation-ajax-getdata', 'DonationController@getData')->name('ajax.getdata');
                Route::get('donation/detail/{id}', 'DonationController@show')->name('donation.show');
                Route::get('donation/{id}/edit', 'DonationController@edit')->name('donation.edit');
                Route::post('donation/{id}', 'DonationController@update')->name('donation.update');
            });

            //VEHICLE
            Route::group(['namespace' => 'Vehicle', 'as' => 'vehicle.'], function () {
                Route::get('vehicle-list', 'VehicleController@index')->name('list');
                Route::get('vehicle-add', 'VehicleController@VehicleAdd')->name('store');
                Route::post('vehicle-add', 'VehicleController@VehiclePost')->name('add');
                Route::get('vehicle/detail/{id}', 'VehicleController@show')->name('show');
                Route::get('vehicle/{id}/edit', 'VehicleController@edit')->name('edit');
                Route::post('vehicle/{id}', 'VehicleController@VehicleUpdate')->name('update');
            });

            //CUSTOMER


             Route::group(['namespace' => 'Customer', 'as' => 'customer.'], function () {

resources/views/dashboard/index.blade.php
@extends('layouts.back-end.sidebar')

@section('content')  
            <div class="col-md-3">

                <div class="block block-drop-shadow" style="cursor: pointer;" onclick="window.location.href='{{route('customer.list')}}'">
                    <div class="head bg-dot20">
                                
                        <div class="head-panel nm">
                            <div class="hp-info pull-left">      
                                <h2>User</h2>                                                          
                            </div>
                            <div class="hp-info pull-left">                                
                            </div>                                                        
                            <div class="hp-info pull-right" style="margin-right: 10%;color: white; ">
                                <div class="hp-icon">                                    
                                </div>                                                 
                                <span class="hp-sm">Active User</span>                                
                                <span class="hp-main"><b>{{\App\Models\User::whereRoleId(1)->whereStatus(1)->count()}}</b></span>                                
                            </div>                            
                        </div>
                    </div>
                </div>
                <div class="block block-drop-shadow" style="cursor: pointer;" onclick="window.location.href='{{route('scavenger.list')}}'">
                    <div class="head bg-dot20">
                                
                        <div class="head-panel nm">
                            <div class="hp-info pull-left">      
                                <h2>Drive</h2>                                                          
                            </div>
                            <div class="hp-info pull-left">                                
                            </div>                                                        
                            <div class="hp-info pull-right" style="margin-right: 10%;color: white;">
                                <div class="hp-icon">                                    
                                </div>                                                 
                                <span class="hp-sm">Active Driver</span>                                
                                <span class="hp-main"><b>{{\App\Models\User::whereRoleId(2)->whereStatus(1)->count()}}</b></span>                                
                            </div>                            
                        </div>
                    </div>
                </div>
                <div class="block block-drop-shadow" style="cursor: pointer;" onclick="window.location.href='{{route('request.list')}}'">
                    <div class="head bg-dot20">
                                
                        <div class="head-panel nm">
                            <div class="hp-info pull-left">      
                                <h2>Recycle</h2>                                                          
                            </div>
                            <div class="hp-info pull-left">                                
                            </div>                                                        
                            <div class="hp-info pull-right" style="margin-right: 10%;color: white;">
                                <div class="hp-icon">                                    
                                </div>                                                 
                                <span class="hp-sm">Total Waste</span>                                
                                <span class="hp-main"><b>{{\App\Models\Request::whereStatus(3)->sum('berat_realisasi')}}</b></span>                                
                            </div>                            
                        </div>
                    </div>
                </div>  
                <div class="block block-drop-shadow" style="cursor: pointer;" onclick="window.location.href='{{route('donation.list')}}'">
                    <div class="head bg-dot20">
                                
                        <div class="head-panel nm">                            
                            <span class="hp-sm" style="color: white;">
                                <span class="icon-download"></span> Total Donation
                            </span>                                
                            <span class="hp-sm pull-right" style="margin-right: 10%;color: white;"><b>{{number_format(\App\Models\Donation::whereStatus(1)->sum('amount'),2,',','.')}}</b></span>
                        </div>
                    </div>
                </div>                            
            </div>
            
            <div class="col-md-5">

                <div class="block block-drop-shadow">
                    <div class="head bg-dot20">
                                
                        <div class="head-panel nm">                            
                            <span class="hp-sm" style="color: white;">
                                <span class="icon-ok"></span> Complete Request
                            </span>                                
                            <span class="hp-sm pull-right" style="margin-right: 10%;color: white;"><b>{{\App\Models\Request::whereStatus(2)->count()}}</b></span>
                        </div>
                    </div>
                </div>
                <div class="block block-drop-shadow">
                    <div class="head bg-dot20">
                                
                        <div class="head-panel nm">                            
                            <span class="hp-sm" style="color: white;">
                                <span class="icon-remove"></span> Cancelled Request
                            </span>                                
                            <span class="hp-sm pull-right" style="margin-right: 10%;color: white;"><b>{{\App\Models\Request::whereStatus(4)->count()}}</b></span>
                        </div>
                    </div>
                </div>
            
                <div class="block block-drop-shadow">
                    <div class="head bg-dot20">
                        <h2 style="padding-left: 35%">Recycle Graphics</h2>                        
                        <div class="head-panel nm">                            
                            <div class="chart" id="dash_chart_custome" style="height: 200px;"></div>
                        </div>                        
                    </div>
                </div> 

            </div>
            
            <div class="col-md-4">
                
                <div class="block block-drop-shadow">
                    <div class="head bg-dot20">

                        <h2 style="padding-left: 35%">5 Top User</h2>

                        <?php $batas = 0; ?>
                        @foreach(\App\Http\Controllers\Rank\RankUserController::queryranktop() as $row)
                                
                        <div class="head-panel nm">
                            <div class="block block-drop-shadow">
                                <div class="head bg-dot110">                                            
                                    <div class="head-panel nm" style="cursor: pointer;" onclick="window.location.href='{{route('customer.edit', $row->id)}}'">
                                        <div class="hp-info pull-left" style="margin-right: 10%">
                                            <div class="hp-icon">
                                                <span class="icon-user"></span>
                                            </div>                                                 
                                            <span class="hp-sm">Name : {{$row->name}} </span> 
                                            <span class="hp-sm">Total Recycle : {{$row->total}}</span>                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                            
                        <?php $batas++; if($batas == 5){break;} ?>
                        @endforeach

                    </div>
                </div>

                <div class="block block-drop-shadow">
                    <div class="head bg-dot20">

                        <h2 style="padding-left: 35%">5 Top Driver</h2>

                        <?php $batas = 0; ?>
                        @foreach(\App\Http\Controllers\Rank\RankUserController::queryranktopscav() as $row)
                                
                        <div class="head-panel nm">
                            <div class="block block-drop-shadow">
                                <div class="head bg-dot110">                                            
                                    <div class="head-panel nm" style="cursor: pointer;" onclick="window.location.href='{{route('scavenger.edit', $row->id)}}'">
                                        <div class="hp-info pull-left" style="margin-right: 10%">
                                            <div class="hp-icon">
                                                <span class="icon-user"></span>
                                            </div>                                                 
                                            <span class="hp-sm">Name : {{$row->name}} </span> 
                                            <span class="hp-sm">Total Recycle : {{$row->total}} Kg.</span>                                
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                            
                        <?php $batas++; if($batas == 5){break;} ?>
                        @endforeach

                    </div>
                </div>
            </div>            
@endsection

@section('scripts')
<script type="text/javascript">
    $(document).ready(function(){
       if($("#dash_chart_custome").length > 0){
        xhr_custome('{{route("get_chartweight")}}')
            .then(function (response) {                        
                var dash_chart_custome = $.plot($("#dash_chart_custome"),
                                    JSON.parse(response),
                                    { 
                                     series: {lines: { show: true }, points: { show: true }},
                                     grid: { hoverable: true, clickable: true, margin: {left: 0}},
                                     xaxis: {ticks: [[1,'Jan'],[2,'Feb'],[3,'Mar'],[4,'Apr'],[5,'May'],[6,'Jun'],[7,'Jul'],[8,'Aug'],[9,'Sep'],[10,'Oct'],[11,'Nov'],[12,'Dec']]},
                                     legend: {show: true}});
            })
            .catch(function (error) {
                console.log('Something went wrong', error);
            });
       }   


    })
</script>
@endsection