routes/web.php
                Route::get('users-ajax-getdata', 'UsersController@getData')->name('ajax.getdata');
                Route::get('users/detail/ajax{id}', 'UsersController@getDataDetail')->name('ajax.getdata.detail');
                Route::get('users/detail/delete/{id}', 'UsersController@detailDelete')->name('detail.delete');

            });    

             // OUR PARTNER //

                Route::group(['namespace' => 'OurPartner', 'as' => 'partner.'], function () {
                    Route::get('partner-list', 'OurPartnerController@index')->name('list');
                    Route::get('partner-add', 'OurPartnerController@PartnerAdd')->name('store');
                    Route::post('partner-add', 'OurPartnerController@PartnerPost')->name('add');

                    Route::get('partner/edit/{id}', 'OurPartnerController@Partneredit')->name('edit');
                    Route::get('partner/delete/{id}', 'OurPartnerController@Partnerdestroy')->name('delete');
                    Route::post('partner/{id}', 'OurPartnerController@update')->name('update');
                    Route::get('partner-ajax-getdata', 'OurPartnerController@getData')->name('ajax.getdata');
                    Route::get('partner/detail/ajax{id}', 'OurPartnerController@getDataDetail')->name('ajax.getdata.detail');
                    Route::get('partner/detail/delete/{id}', 'OurPartnerController@detailDelete')->name('detail.delete');

                });    
        
           // NEWSLETTER //

                Route::group(['namespace' => 'NewsLetter', 'as' => 'newsletter.'], function () {
                    Route::get('newsletter-list', 'NewsLetterController@index')->name('list');
                    Route::get('newsletter-add', 'NewsLetterController@NewsLetterAdd')->name('store');
                    Route::post('newsletter-add', 'NewsLetterController@NewsLetterPost')->name('add');
                    Route::get('newsletter/edit/{id}', 'NewsLetterController@NewsLetteredit')->name('edit');
                    Route::get('newsletter/delete/{id}', 'NewsLetterController@NewsLetterdestroy')->name('delete');
                    Route::post('newsletter/{id}', 'NewsLetterController@update')->name('update');
                });    

            // ABOUT //

            Route::group(['namespace' => 'About', 'as' => 'about.'], function () {
                Route::get('about-list', 'AboutController@index')->name('show');
                Route::post('about-update', 'AboutController@update')->name('update');

            });   

            // ACL //

            Route::group(['namespace' => 'Acl'], function () {

                Route::get('/users-group', 'controller\AclGroupController@index')->name('users-group');
                Route::get('/users-group/create', 'controller\AclGroupController@create')->name('users-group.create');
                Route::post('/users-group', 'controller\AclGroupController@store')->name('users-group.store');
                Route::get('/users-group/{id}', 'controller\AclGroupController@show')->name('users-group.show');
                Route::put('/users-group/{id}', 'controller\AclGroupController@update')->name('users-group.update');
                Route::get('/users-group/delete/{id}', 'controller\AclGroupController@delete')->name('users-group.delete');
            });   


            //SCAVENGER


            Route::group(['namespace' => 'Scavenger', 'as' => 'scavenger.'], function () {

                Route::get('scavenger-list', 'ScavengerController@index')->name('list');
                Route::get('scavenger-add', 'ScavengerController@ScavengerAdd')->name('store');
                Route::post('scavenger-add', 'ScavengerController@ScavengerPost')->name('add');
                Route::get('scavenger/detail/{id}', 'ScavengerController@show')->name('detail');
                Route::get('scavenger/edit/{id}', 'ScavengerController@Scavengersedit')->name('edit');
                Route::post('scavenger/{id}', 'ScavengerController@ScavengerUpdate')->name('update');
                Route::get('scavenger/delete/{id}', 'ScavengerController@Scavengerdestroy')->name('delete');
                Route::post('scavenger/{id}', 'ScavengerController@update')->name('update');
                Route::get('scavenger-ajax-getdata', 'ScavengerController@getData')->name('ajax.getdata');
                Route::get('scavenger/detail/ajax{id}', 'ScavengerController@getDataDetail')->name('ajax.getdata.detail');
                Route::get('scavenger/detail/delete/{id}', 'ScavengerController@detailDelete')->name('detail.delete');
            });

            //DOCUMENT
            Route::group(['namespace' => 'Document', 'as' => 'document.'], function () {
                Route::get('document/detail/{id}', 'DocumentController@documentShow')->name('detail');
                Route::post('document/{id}', 'DocumentController@documentUpdate')->name('update');
                Route::get('document/delete/{id}', 'DocumentController@documentDestroy')->name('delete');
                Route::get('document-ajax-getdata', 'DocumentController@getData')->name('ajax.getdata');
                Route::get('document-ajax-getmodal/{id}', 'DocumentController@getModal')->name('ajax.getmodal');
            });

            //DONATION
            Route::group(['namespace' => 'Donation', 'as' => 'donation.'], function () {
                Route::get('donation-list', 'DonationController@index')->name('list');
                Route::get('donation-ajax-getdata', 'DonationController@getData')->name('ajax.getdata');
                Route::get('donation/detail/{id}', 'DonationController@show')->name('donation.show');
                Route::get('donation/{id}/edit', 'DonationController@edit')->name('donation.edit');
                Route::post('donation/{id}', 'DonationController@update')->name('donation.update');
            });

            //VEHICLE
            Route::group(['namespace' => 'Vehicle', 'as' => 'vehicle.'], function () {
                Route::get('vehicle-list', 'VehicleController@index')->name('list');
                Route::get('vehicle-add', 'VehicleController@VehicleAdd')->name('store');
                Route::post('vehicle-add', 'VehicleController@VehiclePost')->name('add');
                Route::get('vehicle/detail/{id}', 'VehicleController@show')->name('show');
                Route::get('vehicle/{id}/edit', 'VehicleController@edit')->name('edit');
                Route::post('vehicle/{id}', 'VehicleController@VehicleUpdate')->name('update');
            });

            //CUSTOMER


             Route::group(['namespace' => 'Customer', 'as' => 'customer.'], function () {
                Route::get('customer-list', 'CustomerController@index')->name('list');
                Route::get('customer-add', 'CustomerController@CustomerAdd')->name('store');
                Route::post('customer-add', 'CustomerController@CustomerPost')->name('add');
                Route::get('customer/detail/{id}', 'CustomerController@CustomerShow')->name('show');
                Route::get('customer/edit/{id}', 'CustomerController@Customeredit')->name('edit');
                Route::get('customer/delete/{id}', 'CustomerController@Customerdestroy')->name('delete');
                Route::post('customer/{id}', 'CustomerController@update')->name('update');
                Route::get('customer-ajax-getdata', 'CustomerController@getData')->name('ajax.getdata');
                Route::get('customer/detail/ajax{id}', 'CustomerController@getDataDetail')->name('ajax.getdata.detail');
                Route::get('customer/detail/delete/{id}', 'CustomerController@detailDelete')->name('detail.delete');
                Route::get('customer/myrecycle', 'CustomerController@myRecycle')->name('myrecycle');


            });

             //REQUEST


             Route::group(['namespace' => 'Request', 'as' => 'request.'], function () {
                Route::get('request-list', 'RequestController@index')->name('list');
                Route::get('request-add', 'RequestController@RequestAdd')->name('store');
                Route::post('request-add', 'RequestController@RequestPost')->name('add');
                Route::get('request/detail/{id}', 'RequestController@show')->name('detail');
                Route::get('request/edit/{id}', 'RequestController@Requestedit')->name('edit');
                Route::get('request/delete/{id}', 'RequestController@Requestdestroy')->name('delete');
                Route::post('request/{id}', 'RequestController@update')->name('update');
                Route::get('request-ajax-getdata', 'RequestController@getDatarequest')->name('ajax.getdata');
                Route::get('request/detail/ajax{id}', 'RequestController@getDataDetail')->name('ajax.getdata.detail');
                Route::get('request/detail/delete/{id}', 'RequestController@detailDelete')->name('detail.delete');

            });
             
    //category
              Route::group(['namespace' => 'Category', 'as' => 'category.'], function () {
                Route::get('category-list', 'CategoryController@index')->name('list');
                // Route::get('category-test', 'CategoryController@index')->name('list');
                Route::get('category-add', 'CategoryController@CategoryAdd')->name('add');
                Route::post('category-store', 'CategoryController@categoryPost')->name('store');
                Route::get('category/detail/{id}', 'CategoryController@show')->name('detail');
                
                Route::get('category/edit/{id}', 'CategoryController@Categoryedit')->name('edit');
                Route::get('category/delete/{id}', 'CategoryController@categorydestroy')->name('delete');
                Route::post('category/{id}', 'CategoryController@update')->name('update');
                Route::get('category-ajax-getdata', 'CategoryController@getDatacategory')->name('ajax.getdata');

app/Http/Controllers/Scavenger/ScavengerController.php
<?php

namespace App\Http\Controllers\Scavenger;

use App\Models\Document;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Session;
use Redirect;

class ScavengerController extends Controller
{

      public function __construct()
     {
         $this->middleware('auth', ['except' => ['total_obp_driver']]);
     }

    
    public function index(){
        $scavengers          = User::orderBy('created_at','desc')->get();
        $this->data['title'] = "Scavenger List";

        return view('scavenger.view.list', ['scavengers'=>$scavengers], $this->data);
 
    }

    public function show($id)
    {
        try{
            $scavengers            = \App\Models\User::find($id);
            $this->data['title']   = 'Scavenger Detail';
            $this->data['ratings'] = \App\Models\Rating::whereScavengerId($id)->get();

            return view('scavenger.view.detail', compact('scavengers'), $this->data);
        }
        catch (\Exception $e) {
            return $e->getMessage();
        }
    }

//    public function getData(){
//
//    $users = \App\Models\User::all();
//
//     $i		= 0;
//     $data	= [];
//     $output = array(
//           "data" => []
//       );
//
//
//     foreach ($users as $index=>$list){
//         if ($list->role_id == 1){
//               $link_edit = url('/admin/scavenger/edit').'/'.$list->id ;
////             $link_delete = url('/admin/scavenger/delete').'/'.$list->id ;
//             // $edits = User::where('id',$list->id)->first();
//             // $roles = \App\UserGroup::find($list->roles);
//             $output['data'][$i][]    = $i+1;
//             $output['data'][$i][]    = $list->first_name;
//             // $output['data'][$i][]    = '<a href="'.$link_edit.'" >'.$list->first_name.'</a>';
//             if ($list->gender == 'L'){
//                 $output['data'][$i][] = 'Laki laki';
//             }
//             elseif ($list->gender == 'P' || $list->gender == 'W'){
//                 $output['data'][$i][] = 'Perempuan';
//             }else{
//                 $output['data'][$i][] = '';
//             }
////             $output['data'][$i][]    = $list->gender;
//             $output['data'][$i][]    = $list->date_of_birth;
//             $output['data'][$i][]    = $list->email;
//             $output['data'][$i][]    = $list->mobile;
//             $output['data'][$i][]    = $list->status;
//             $output['data'][$i][]    = Carbon::parse($list->created_at)->format('d M Y - H:i:s');
////             $output['data'][$i][]    = $list->created_by;
////             $output['data'][$i][]    = '<center><a href="'.$link_edit.'" data-popup="tooltip" title="Edit users"><i class="icon-edit"></i></a> || <a href="'.$link_delete.'" data-popup="tooltip" title="Delete users"><i class="icon-remove-sign"></i></a></center>';
//             $i++;
//         }
//         else{
//             '';
//         }
//        }
//        return json_encode($output);
//
//    }

    public function ScavengerAdd(){

        // return view('Users.view.add');
    }

    public function ScavengerPost(Request $request){

        // $input                        = $request->all();
        // $input['password']            = bcrypt($request->password);
        // $input['image']               = "";

        // $store                        = \App\Models\Admin::create($input);

        //  return redirect('/admin/users-list')->with('status', 'User Success Added!');;
    }

    public function Scavengerdestroy($id){

//       $data= \App\Models\Admin::find($id);
//       $data->delete();
//       return redirect('/admin/users-list')->with('status', 'User Success Deleted!');
    }

    public function Scavengersedit($id){
        
        $this->data['title'] = "Scavenger Edit";
        $this->data['data'] = \App\Models\User::find($id);
        return view('scavenger.view.edit',$this->data);
   }

    public function update(Request $request, $id)
    {
        $update = new \App\Models\User;
        $update = User::find($id);
        $update->status = $request->status;
        $update->note_verify = $request->note_verify;

        $count = $request->countDoc;
        for($i=0; $i<=$count; $i++){
            $updDoc = new \App\Models\Document;
            $updDoc->scavenger_id = $request->idScavenger;
            define('UPLOAD_DIR'.$i, 'storage/app/');
            $image       = uniqid().".png";


            if($i==0){
                $imgpicture  = $request->file('image')->storeAs('images', $image);
                $updDoc->image = $image;
                $updDoc->type = $request->type;
            }else{

                $img = 'image'.$i;
                $type = 'type'.$i;
                $imgpicture  = $request->file(''.$img)->storeAs('images', $image);
                $updDoc->image = $image;
                $updDoc->type = $request->$type;
            }
            $updDoc->save();
        }

        $update->update();

         return redirect('/admin/scavenger-list')->with('status', 'Scavenger Success Edited!');
     }

    public function total_obp_driver(Request $request)
    {
        # code...
        $id     = $request->input('scavenger_id');
        $data   = \DB::select('SELECT t5.* FROM (SELECT t4.*, @rank := @rank + 1 AS rank FROM (SELECT *, (t3.total_order + (t3.point / 100000)) AS total_akhir FROM (SELECT 
t1.*, 
CASE WHEN t2.point IS NOT NULL 
       THEN t2.point
       ELSE 0
END AS point,
CONCAT(t6.first_name," ",t6.last_name) AS name
FROM (SELECT
    scavanger_id,        
    CASE WHEN SUM(berat_realisasi) IS NOT NULL 
           THEN SUM(berat_realisasi)
           ELSE 0
    END AS total_weight,
    COUNT(*) AS total_order
FROM scavanger_requests WHERE scavanger_id = '.$id.'
GROUP BY  scavanger_id ) t1 LEFT JOIN scavanger_points t2 ON t1.scavanger_id = t2.user_id INNER JOIN scavanger_users t6 ON t6.id = t1.scavanger_id WHERE t6.role_id = 2) t3  ORDER BY (t3.total_order + (t3.point / 100000)) DESC) t4 , (SELECT @rank := 0) r) t5 ORDER BY t5.rank');

        if(count($data) > 0){

            $result = array('result'=> 1, 'message'=> 'success', 'data' => [
                'total_order' => $data[0]->total_order,
                'total_weight' => $data[0]->total_weight,
                'total_point' => $data[0]->point,
            ]);
        } else {
            $result = array('result'=> 1, 'message'=> 'success', 'data' => [
                'total_order' => 0,
                'total_weight' => 0,
                'total_point' => 0,
            ]);
        }

        return $result;
    }
}

resources/views/scavenger/view/list.blade.php
@extends('layouts.back-end.sidebar')

@section('content')
        <!-- Breadcrumb -->
<style>
    select[name="table-scavenger_length"] {
        width: 75px;
    }

    div[class="dataTables_length"] {
        width: 300px;
    }

    div[class="dataTables_filter"] {
        /*margin-top: 5px;*/
        margin-left: 90%;
    }

    div.dt-buttons{
        color: black;
        float: right;
        
    }

    button[class="dt-button buttons-excel buttons-html5"]{
    /*background-color: green;*/
      color: #ffffff;
      font-weight: bold;
      text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
      background-image: -webkit-linear-gradient(top, #00cc00 0%, #00cc00 100%);
      background-image: -o-linear-gradient(top, #00cc00 0%, #00cc00 100%);
      background-image: linear-gradient(to bottom, #00cc00 0%, #00cc00 100%);
      /*background-color: #00cc00;*/
      background-image: -moz-linear-gradient(top, rgb(0,146,69), rgb(0,146,69));
      background-image: -webkit-gradient(linear, 0 0, 0 100%, from(rgb(0,146,69)), to(rgb(0,146,69)));
      background-image: -webkit-linear-gradient(top, rgb(0,146,69), rgb(0,146,69));
      background-image: -o-linear-gradient(top, rgb(0,146,69), rgb(0,146,69));
      background-image: linear-gradient(to bottom, rgb(0,146,69), rgb(0,146,69));
      background-repeat: repeat-x;
      filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff00cc00', endColorstr='#ffe34619', GradientType=0);
      border-color: #00cc00 #00cc00 #00cc00;
      border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
      background-color: rgb(0,146,69);
      /* Darken IE7 buttons by default so they stand out more given they won't have borders */
      filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
      width:50px;
      height: 30px;

    }

    button[class="dt-button buttons-pdf buttons-html5"]{
      color: #ffffff;
      font-weight: bold;
      text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
      background-image: -webkit-linear-gradient(top, rgb(0,146,69) 0%, rgb(0,146,69) 100%);
      background-image: -o-linear-gradient(top, rgb(0,146,69) 0%, rgb(0,146,69) 100%);
      background-image: linear-gradient(to bottom, rgb(0,146,69) 0%, rgb(0,146,69) 100%);
      background-color: rgb(0,146,69);
      background-image: -moz-linear-gradient(top, rgb(0,146,69), rgb(0,146,69));
      background-image: -webkit-gradient(linear, 0 0, 0 100%, from(rgb(0,146,69)), to(rgb(0,146,69)));
      background-image: -webkit-linear-gradient(top, rgb(0,146,69), rgb(0,146,69));
      background-image: -o-linear-gradient(top, rgb(0,146,69), rgb(0,146,69));
      background-image: linear-gradient(to bottom, rgb(0,146,69), rgb(0,146,69));
      background-repeat: repeat-x;
      filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffff0000', endColorstr='#ffe34619', GradientType=0);
      border-color: #ff0000 #ff0000 #ff0000;
      border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
      /**background-color: #ff0000;*/
      background-color: rgb(0,146,69);
      /* Darken IE7 buttons by default so they stand out more given they won't have borders */
      filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
      margin-left: 10px;
      width:50px;
      height: 30px;
    }
</style>


<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb">
            <li><a href="{{url('admin/home')}}">Home</a></li>
            <li><a href="{{url('admin/scavenger-list')}}">Scavenger</a></li>
            <li class="active">List</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        @if (session('status'))
            <div class="alert alert-success">
                <strong>{{ session('status') }}.</strong>
                <button type="button" class="close" data-dismiss="alert">×</button>

            </div>
        @endif
        <div class="block">
            <div class="header">
                <h2 style="color: rgb(0,146,69)">Scavenger List</h2>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <button class="btn btn-primary" onclick="reloadPage()" style="background-color: rgb(0,146,69); border-color: rgb(0,146,69)">Refresh</button>

                <div class="side pull-right">
                    <ul class="buttons">
                        <li class="btn-group">

                        </li>
                        <li><a href="#" class="block-toggle tip" title="Toggle content"><span
                                        class="icon-chevron-down"></span></a></li>

                    </ul>
                </div>
            </div>
            <hr>
            <div class="content">
                <table class="table table-bordered table-striped table-hover" id="table-scavenger">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Gender</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Created At</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; ?>
                    @foreach($scavengers as $index => $scavenger)
                        @if($scavenger->role_id == 2)
                            <tr class="clicklable-row" data-href="{{url('/admin/scavenger/detail', $scavenger->id)}}">
                                <td>{{$i++}}</td>
                                <td>{{$scavenger->name}}</td>
                                @if($scavenger->gender == 'L')
                                    <td>Male</td>
                                @elseif($scavenger->gender == null)
                                    <td>-</td>
                                @else
                                    <td>Female</td>
                                @endif
                                <td>{{$scavenger->email}}</td>
                                @if($scavenger->status == 'Verified' || $scavenger->status == 1)
                                    <td>Verified</td>
                                @elseif($scavenger->status == 'Unverified' || $scavenger->status == 0)
                                    <td>Unverified</td>
                                @else
                                    <td>-</td>
                                @endif
                                <td>{{\Carbon\Carbon::parse($scavenger->created_at)->format('d M Y - H:i:s')}}</td>
                            </tr>
                        @else
                        @endif
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

    <script type="text/javascript">

        $('#table-scavenger').dataTable({
            "aLengthMenu": [10, 50, 100],
            "dom": 'lBfrtip',
            "buttons": [
                {
                    extend: 'excelHtml5',
                    title: 'Scavenger List'
                },
                {
                    extend: 'pdfHtml5',
                    title: 'Scavenger List'
                },
              ],
        });

        jQuery(document).ready(function ($) {
            $("#table-scavenger").on('click', '.clicklable-row', function () {
                window.location = $(this).data("href");
            });
            $("#table-scavenger").css('cursor', 'pointer');
            $("#table-scavenger").hover(function () {
                $(this).css('cursor', 'pointer');
            });
        });

        {{--$(document).ready(function(){--}}
        //        var table = $('#example').DataTable({
        //            "aLengthMenu": [10,50,100],
        //        });

        {{--table.ajax.url('{{route("scavenger.ajax.getdata")}}').load();--}}
        {{--});--}}

        function reloadPage()
        {
            location.reload();
        }

    </script>
@endsection