routes/web.php
<?php


// Auth::loginUsingId(1);

// Auth::routes();
    
Route::group(array('domain' => Config("subdom.second_dom")), function () {
    
    Route::get('/590d38f0603ef5a8a7be6c452438d609/{id}', 'Customer\CustomerHelper@verificationuser')->name('verificationuser');
    Route::get('/donate', function(){
            return \view('donateview');
    })->name('donateview');

    // Password Reset Routes...
    // Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    // Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    // Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::get('user/change-password/{token}', 'MailService\MailServiceController@forgotpasswordform')->name('changepassword');
    Route::post('user/change-password', 'MailService\MailServiceController@forgotpasswordpost')->name('changepasswordpost');
    Route::post('user/reset-password', 'MailService\MailServiceController@forgotpassword');

});

    Route::get('testt', function(){
        $user = \App\Models\User::find(239);
        return \App\Http\Controllers\MailService\MailServiceController::KonfirmasiPendaftaran($user);
    });
Route::group(array('domain' => Config("subdom.first_dom")), function () {



    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    // Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    Route::get('/admin/logout','HomeController@logout')->name('logout');
    // Registration Routes...
    // Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    // Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');


    Route::get('/','HomeController@index')->name('index');
    Route::group(['prefix' => 'admin', 'middleware' => 'superadmin'], function() {
                
        Route::get('/home', 'HomeController@dashboard')->name('dashboard');
            
            // USERS //

            Route::group(['namespace' => 'Users', 'as' => 'users.'], function () {
                Route::get('users-list', 'UsersController@index')->name('list');
                Route::get('users-add', 'UsersController@UsersAdd')->name('store');
                Route::post('users-add', 'UsersController@UsersPost')->name('add');
                Route::get('users/detail/{id}', 'UsersController@show')->name('detail');
                Route::get('users/edit/{id}', 'UsersController@Usersedit')->name('edit');
                Route::get('users/delete/{id}', 'UsersController@Usersdestroy')->name('delete');
                Route::post('users/{id}', 'UsersController@update')->name('update');
                Route::get('users-ajax-getdata', 'UsersController@getData')->name('ajax.getdata');
                Route::get('users/detail/ajax{id}', 'UsersController@getDataDetail')->name('ajax.getdata.detail');
                Route::get('users/detail/delete/{id}', 'UsersController@detailDelete')->name('detail.delete');

            });    

             // OUR PARTNER //

                Route::group(['namespace' => 'OurPartner', 'as' => 'partner.'], function () {
                    Route::get('partner-list', 'OurPartnerController@index')->name('list');
                    Route::get('partner-add', 'OurPartnerController@PartnerAdd')->name('store');
                    Route::post('partner-add', 'OurPartnerController@PartnerPost')->name('add');

                    Route::get('partner/edit/{id}', 'OurPartnerController@Partneredit')->name('edit');
                    Route::get('partner/delete/{id}', 'OurPartnerController@Partnerdestroy')->name('delete');
                    Route::post('partner/{id}', 'OurPartnerController@update')->name('update');
                    Route::get('partner-ajax-getdata', 'OurPartnerController@getData')->name('ajax.getdata');
                    Route::get('partner/detail/ajax{id}', 'OurPartnerController@getDataDetail')->name('ajax.getdata.detail');
                    Route::get('partner/detail/delete/{id}', 'OurPartnerController@detailDelete')->name('detail.delete');

                });    
        
           // NEWSLETTER //

                Route::group(['namespace' => 'NewsLetter', 'as' => 'newsletter.'], function () {
                    Route::get('newsletter-list', 'NewsLetterController@index')->name('list');
                    Route::get('newsletter-add', 'NewsLetterController@NewsLetterAdd')->name('store');
                    Route::post('newsletter-add', 'NewsLetterController@NewsLetterPost')->name('add');
                    Route::get('newsletter/edit/{id}', 'NewsLetterController@NewsLetteredit')->name('edit');
                    Route::get('newsletter/delete/{id}', 'NewsLetterController@NewsLetterdestroy')->name('delete');
                    Route::post('newsletter/{id}', 'NewsLetterController@update')->name('update');
                });    

            // ABOUT //

            Route::group(['namespace' => 'About', 'as' => 'about.'], function () {
                Route::get('about-list', 'AboutController@index')->name('show');
                Route::post('about-update', 'AboutController@update')->name('update');

            });   

            // ACL //

            Route::group(['namespace' => 'Acl'], function () {

                Route::get('/users-group', 'controller\AclGroupController@index')->name('users-group');
                Route::get('/users-group/create', 'controller\AclGroupController@create')->name('users-group.create');
                Route::post('/users-group', 'controller\AclGroupController@store')->name('users-group.store');
                Route::get('/users-group/{id}', 'controller\AclGroupController@show')->name('users-group.show');
                Route::put('/users-group/{id}', 'controller\AclGroupController@update')->name('users-group.update');
                Route::get('/users-group/delete/{id}', 'controller\AclGroupController@delete')->name('users-group.delete');
            });   


            //SCAVENGER


            Route::group(['namespace' => 'Scavenger', 'as' => 'scavenger.'], function () {

                Route::get('scavenger-list', 'ScavengerController@index')->name('list');
                Route::get('scavenger-add', 'ScavengerController@ScavengerAdd')->name('store');
                Route::post('scavenger-add', 'ScavengerController@ScavengerPost')->name('add');
                Route::get('scavenger/detail/{id}', 'ScavengerController@show')->name('detail');
                Route::get('scavenger/edit/{id}', 'ScavengerController@Scavengersedit')->name('edit');
                Route::post('scavenger/{id}', 'ScavengerController@ScavengerUpdate')->name('update');
                Route::get('scavenger/delete/{id}', 'ScavengerController@Scavengerdestroy')->name('delete');
                Route::post('scavenger/{id}', 'ScavengerController@update')->name('update');
                Route::get('scavenger-ajax-getdata', 'ScavengerController@getData')->name('ajax.getdata');
                Route::get('scavenger/detail/ajax{id}', 'ScavengerController@getDataDetail')->name('ajax.getdata.detail');
                Route::get('scavenger/detail/delete/{id}', 'ScavengerController@detailDelete')->name('detail.delete');
            });

            //DOCUMENT
            Route::group(['namespace' => 'Document', 'as' => 'document.'], function () {
                Route::get('document/detail/{id}', 'DocumentController@documentShow')->name('detail');
                Route::post('document/{id}', 'DocumentController@documentUpdate')->name('update');
                Route::get('document/delete/{id}', 'DocumentController@documentDestroy')->name('delete');
                Route::get('document-ajax-getdata', 'DocumentController@getData')->name('ajax.getdata');
                Route::get('document-ajax-getmodal/{id}', 'DocumentController@getModal')->name('ajax.getmodal');
            });

            //DONATION
            Route::group(['namespace' => 'Donation', 'as' => 'donation.'], function () {
                Route::get('donation-list', 'DonationController@index')->name('list');
                Route::get('donation-ajax-getdata', 'DonationController@getData')->name('ajax.getdata');
                Route::get('donation/detail/{id}', 'DonationController@show')->name('donation.show');
                Route::get('donation/{id}/edit', 'DonationController@edit')->name('donation.edit');
                Route::post('donation/{id}', 'DonationController@update')->name('donation.update');
            });

            //VEHICLE
            Route::group(['namespace' => 'Vehicle', 'as' => 'vehicle.'], function () {
                Route::get('vehicle-list', 'VehicleController@index')->name('list');
                Route::get('vehicle-add', 'VehicleController@VehicleAdd')->name('store');
                Route::post('vehicle-add', 'VehicleController@VehiclePost')->name('add');
                Route::get('vehicle/detail/{id}', 'VehicleController@show')->name('show');
                Route::get('vehicle/{id}/edit', 'VehicleController@edit')->name('edit');
                Route::post('vehicle/{id}', 'VehicleController@VehicleUpdate')->name('update');
            });

            //CUSTOMER


             Route::group(['namespace' => 'Customer', 'as' => 'customer.'], function () {

resources/views/layouts/include/nav.blade.php
   <nav class="navbar brb" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-reorder"></span>                            
                </button> 
                <a class="navbar-brand" href="{{route('dashboard')}}"><img src="{{ asset('public/back-end/img/scavenger.png') }}" height="85%"></a>                         
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">                                     
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{{ route('dashboard') }}">
                            <span class="icon-home"></span> Dashboard
                        </a>
                    </li>                            
                       
                  
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-user"></span>User</a>

                         <ul class="dropdown-menu" style="background-color: rgb(0,146,69)">
                            <!-- <li><a href="">Master</a></li>  -->
                            <li>
                                <a href="#">Transaction<i class="icon-angle-right pull-right"></i></a>
                                        <ul class="dropdown-submenu" style="background-color: rgb(0,146,69)">
                                            <li><a href="{{ route('customer.list') }}">User List</a></li>
                                                                                        
                                        </ul>
                            </li>  
                                 
                            <!-- <li><a href="#">Report</a></li>           -->

                        </ul>
                    </li>  
                     <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-trash"></span>RECYCLE</a>
                        <ul class="dropdown-menu" style="background-color: rgb(0,146,69)">
                            <li>
                                <a href="#">Master<i class="icon-angle-right pull-right"></i></a>
                                        <ul class="dropdown-submenu" style="background-color: rgb(0,146,69)">
                                            <li><a href="{{ route('category.list') }}">Category Setup</a></li>
                                                                                        
                                        </ul>
                            </li> 
                            <li>
                                <a href="#">Transaction<i class="icon-angle-right pull-right"></i></a>
                                        <ul class="dropdown-submenu" style="background-color: rgb(0,146,69)">
                                            <li><a href="{{ route('request.list') }}">Recycle List</a></li>
                                                                                        
                                        </ul>
                            </li>  
                                <ul class="dropdown-submenu">
                                    <li><a href="">Transaction</a></li>

                                </ul>  
                            <li>
                                <a href="#">Report<i class="icon-angle-right pull-right"></i></a>
                                        <ul class="dropdown-submenu" style="background-color: rgb(0,146,69)">
                                            <li><a href="{{ route('report.list') }}">Category Report</a></li>
                                            <li><a href="{{ route('report.list-requestreport') }}">Request Report</a></li>
                                                                                        
                                        </ul>
                            </li>           

                        </ul>
                    </li>   
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-trash"></span>Scavenger</a>
                        <ul class="dropdown-menu" style="background-color: rgb(0,146,69)">
                            <li>
                                <a href="#">Transaction<i class="icon-angle-right pull-right"></i></a>
                                        <ul class="dropdown-submenu" style="background-color: rgb(0,146,69)">
                                            <li><a href="{{ route('scavenger.list') }}">Scavenger</a></li>
                                                                                        
                                        </ul>
                            </li>  
                                <ul class="dropdown-submenu" style="background-color: rgb(0,146,69)">
                                    <li><a href="">Transaction</a></li>
                                </ul>           
                        </ul>
                    </li>        
                     <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-trash"></span>Donation</a>
                        <ul class="dropdown-menu" style="background-color: rgb(0,146,69)">

                            <!-- <li><a href="#">Master</a></li> -->
                            <li>
                                <a href="#">Transaction<i class="icon-angle-right pull-right"></i></a>
                                        <ul class="dropdown-submenu" style="background-color: rgb(0,146,69)">
                                            <li><a href="{{ route('donation.list') }}">Donation</a></li>
                                        </ul>
                            </li>
                            <!-- <li><a href="#">Report</a></li> -->
                         
                        </ul>
                    </li>       
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-cog"></span> Setting</a>
                        <ul class="dropdown-menu" style="background-color: rgb(0,146,69)">
                            <li><a href="{{ route('about.show') }}">About Us</a></li>          
                            <li><a href="{{ route('newsletter.list') }}">Newsletter</a></li>          
                            <li><a href="{{ route('vehicle.list') }}">Vehicle</a></li>
                            <li><a href="{{ route('partner.list') }}">Our Partner</a></li>
                            <li><a href="{{ route('users.list') }}">Admin List</a></li>        
                            <li><a href="{{ route('users-group') }}">Permision Group</a></li>        
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="{{ route('logout') }}" ><span class="icon-off"></span> Logout</a>
                       
                    </li>       
                     
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="search..."/>
                    </div>                            
                </form>                                            
            </div>
        </nav>  